<?php

return [
    'products_seed' => [
        [
            'id' => 1,
            'sku' => 'P0001',
            'slug' => 'p/maillot-ciclismo-manga-larga-hombre-m2-gravel',
            'name' => 'M2 Gravel, Maillot de manga larga hombre',
            'description' => 'Pensado para los más inconformistas. Si te gusta marcar tu propio camino, descubre el nuevo Siroko Gravel: un maillot de una comodidad extraordinaria proporcionada por su corte Race Slim Fit y estilo unisex que garantiza un ajuste perfecto en cuello y cintura. Manga larga 100% aerodinámica perfecta para las salidas de entretiempo. Cuenta con una transpiración óptima gracias a la incorporación de nuevos tejidos de última generación y tecnología Breathlock+ que combinan poliéster y spandex para lograr la máxima elasticidad. Cremallera SBS Full Hidden con costura doble y anti-rozamiento. 3 cómodos bolsillos en la parte trasera y detalle reflectante de seguridad. Convierte la tierra y el polvo en un modo de vida.',
            'image' => 'https://cdn.siroko.com/products/666829ffcdd86/1200x/crop_center.webp?v=1718109852',
            'parent_id' => null,
            'category_id' => 1,
            'enabled' => 1,
        ],
        [
            'id' => 2,
            'sku' => 'P0001-001',
            'name' => 'M2 Gravel, Maillot de manga larga hombre - Black - Size M',
            'image' => 'https://cdn.siroko.com/products/66682a0456a28/1200x/crop_center.webp',
            'parent_id' => 1,
            'category_id' => 1,
            'enabled' => 1,
            'size' => 'M',
            'color' => 'black',
            'price' => 59.95,
            'stock' => 100,
        ],
        [
            'id' => 3,
            'sku' => 'P0001-002',
            'name' => 'M2 Gravel, Maillot de manga larga hombre - Black - Size L',
            'image' => 'https://cdn.siroko.com/products/66682a0666a56/1200x/crop_center.webp?v=1718109852',
            'parent_id' => 1,
            'category_id' => 1,
            'enabled' => 1,
            'size' => 'L',
            'color' => 'black',
            'price' => 59.95,
            'stock' => 50,
        ],
        [
            'id' => 4,
            'sku' => 'P0002',
            'slug' => 'p/cortavientos-ciclismo-v1-langkawi-amarillo-neon',
            'name' => 'V1 Langkawi, Chaleco cortavientos ciclismo hombre',
            'description' => 'El amor por el ciclismo ya ha conquistado los cinco continentes. ¿Serías capaz de recorrer el mundo en bicicleta? El cortavientos Langkawi ha sido confeccionado con tejido 100% poliéster ultraligero capaz de evitar la pérdida de calor por convección. Su diseño, de ajuste perfecto, incorpora todo lo que necesitas en la zona frontal para una protección total frente al viento. En la espalda cuenta con un panel de tejido micromesh que favorece una transpiración perfecta. Incluye cremallera SBS, bolsillo y un detalle reflectante de máxima visibilidad en la parte trasera para la seguridad del ciclista. También dispone de dos aperturas laterales traseras que te facilitarán el acceso a los bolsillos de tu maillot. Se pliega en su bolsillo central para que puedas transportarlo con la mayor comodidad. Ideal para salidas con temperaturas frescas y largos descensos en los que el viento puede ser tu peor enemigo. La aventura solo acaba de empezar.',
            'image' => 'https://cdn.siroko.com/products/668cf972a640d/1200x/crop_center.webp?v=1720522318',
            'parent_id' => null,
            'category_id' => 1,
            'enabled' => 1,
        ],
        [
            'id' => 5,
            'sku' => 'P0002-001',
            'name' => 'V1 Langkawi, Chaleco cortavientos ciclismo hombre - Yellow - Size M',
            'image' => 'https://cdn.siroko.com/products/668cf96e6280c/1200x/crop_center.webp?v=1720522318',
            'parent_id' => 4,
            'category_id' => 1,
            'enabled' => 1,
            'size' => 'M',
            'color' => 'yellow',
            'price' => 39.95,
            'stock' => 3,
        ],
    ]
];
